<?php

namespace Taller\Bundle\GageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaRepository extends EntityRepository
{
}
